name: CI
on:
    push:

jobs:
    main:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432
        env:
            DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres

        strategy:
            matrix:
                node-version: [17.x]

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: pnpm/action-setup@v2.4.0
              with:
                  version: latest
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
            - uses: nrwl/nx-set-shas@v3

            - run: pnpm install # not pnpm ci

            - run: pnpm prisma migrate deploy

            - run: pnpm exec nx format:check
            - run: pnpm exec nx affected --target=lint --parallel=3
            - run: pnpm exec nx affected --target=test --parallel=3 --ci --code-coverage
            - run: pnpm exec nx affected --target=build --parallel=3
